#!/bin/bash

usage() {
	echo "Usage: $(basename "$0") [-h] artifact_name config [artifact_version]"
}
while getopts "h" arg; do
	case $arg in
	h)
		usage
		exit 0
		;;
	*)
		usage
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))
if [[ $# -ne 2 ]] && [[ $# -ne 3 ]]; then
	usage
	exit 0
fi

readonly artifact=$1
readonly config=$2
artifact_version=$3
set -e

versions=()

if [[ $# -eq 3 ]]; then
	source_path=$(ore-artifact "$artifact" "$artifact_version")
	versions+=("$artifact_version")

elif [[ $# -eq 2 ]]; then
	hasVersion=$(echo "$config" | yq -r '.versions // ""')
	if [[ -n "$hasVersion" ]]; then
		mapfile -t versions < <(echo "$config" | yq -r '.versions[]')
	else # latest version
		source_path=$(ore-artifact -l "$artifact")
		artifact_version=$("$ORE_LIB_HOME/ore-artifact-get-version-from-path" "$artifact" "$source_path")
		versions+=("$artifact_version")
		echo.debug "latest artifact_version: $artifact_version"

	fi
fi

target_home=$(ore-config .artifacts.distribution.app)
mkdir -p "$target_home"

for artifact_version in "${versions[@]}"; do

	source_path=$(ore-artifact "$artifact" "$artifact_version")
	echo.debug "Source path: $source_path"

	target_basename=${artifact}-${artifact_version}
	target_path=$target_home/$target_basename

	if [[ -d $target_path ]]; then
		echo.debug "Distribute $artifact: $artifact_version already exists."
	else

		echo "Distribute $artifact: $artifact_version"
    extract_method=$("$ORE_LIB_HOME/ore-artifact-get-extract-method" "$artifact" "$source_path")
		create_directory=$(echo "$config" | yq -r '.createDirectory // ""')

		echo.debug "Extract method: $extract_method"
		echo.debug "Create directory: $create_directory"

		if [[ -z $extract_method ]]; then
			echo.error "Cannot determine extract method for $artifact from $source_path"
			exit 1
		fi

		tempDir=$(mktemp -d --tmpdir "$(basename "$0")-XXXXXXXXXX")
		cd "$tempDir" || exit 1

		(
			if is-true "$create_directory"; then
				mkdir -p "$target_basename"
				cd "$target_basename"
			fi

			if [[ "$extract_method" == "zip" ]]; then
				unzip -q "$source_path"

			elif [[ "$extract_method" == "tar" ]]; then

				tar xf "$source_path"

			else
				echo.error "Unsupported extract method: $extract_method"
				exit 1
			fi
		)
		dirName=$(find . -maxdepth 1 -type d -not -name ".*")
		touch "$dirName"
		mv "$dirName" "$target_path"
		(cd "$target_home" && ln -s -f -T "$target_basename" "$artifact")

	fi
done
