#!/bin/bash

usage() {
	echo "Usage: $(basename "$0") [-h] artifact_name config [artifact_version]"
}
while getopts "h" arg; do
	case $arg in
	h)
		usage
		exit 0
		;;
	*)
		usage
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))
if [[ $# -ne 2 ]] && [[ $# -ne 3 ]]; then
	usage
	exit 0
fi

readonly artifact=$1
# config ($2) is not used in bin distribution, but keep it for consistent interface
artifact_version=$3
set -e

target_home=$(ore-config .artifacts.distribution.jarcli)
mkdir -p "$target_home"

if [[ $# -eq 2 ]]; then
	source_path=$(ore-artifact -l "$artifact")

elif [[ $# -eq 3 ]]; then
	source_path=$(ore-artifact "$artifact" "$artifact_version")
	if [[ ! -f $source_path ]]; then
		echo.error "$artifact version $artifact_version not exist"
		exit 1
	fi
fi
install_version=$("$ORE_LIB_HOME/ore-artifact-get-version-from-path" "$artifact" "$source_path")
echo.debug "Install version: $install_version"

target_basename=${artifact}
target_path=$target_home/$target_basename
config=$(ore-config '.distribution |  to_entries | .[] | .value[]| select(.name == "'"$artifact"'")')

artifact_java_path=$(echo "$config" | yq -r '.javaPath // ""')
default_java_path=$(ore-config  '.defaultJavaPath // "java"')
java_path=${artifact_java_path:-$default_java_path}
echo.debug "Using java path: $java_path"

# shellcheck disable=SC2145
echo "#!/bin/bash

exec \"$java_path\" -jar \"$source_path\" \"\$@\"
" >"$target_path"
chmod +x "$target_path"
