#!/bin/bash

usage() {
	echo "Usage: $(basename "$0") [-h] artifact_name config"
}
while getopts "h" arg; do
	case $arg in
	h)
		usage
		exit 0
		;;
	*)
		usage
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))
if [[ $# -ne 2 ]]; then
	usage
	exit 0
fi

readonly artifact=$1
readonly config=$2

zip_home=$(ore-artifact "$artifact")
mkdir -p "$zip_home"

alwaysDownload=$(echo "$config" | yq -r '.alwaysDownload // ""')
is-true "$alwaysDownload" && echo.debug "alwaysDownload is on"

exit_code=0
while IFS=, read -r url name; do

	filename=${name:-$(basename "$url")}
	target_path="$(ore-artifact "$artifact")"/"$filename"

	if ! is-true "$alwaysDownload" && [[ -f $target_path ]]; then
		echo.debug "$target_path already exists." >&2
	else
		if ! curl -L --fail "$url" -o "$target_path"; then
			echo.error "Failed to download $url"
			((exit_code++))
		fi
	fi
done < <(echo "$config" | yq -r '.urls[]|[.url, .name]|join(",")')

exit $exit_code
