name: Build with Quality Check
on:
  push:
    branches:
      - "*"
  workflow_call:

jobs:
  shellcheck:
    uses: ./.github/workflows/shellcheck.yml
  build-deb:
    uses: ./.github/workflows/build-deb.yml
    needs: shellcheck
  build-rpm:
    uses: ./.github/workflows/build-rpm.yml
    needs: shellcheck
  # bats-test:
  #   uses: ./.github/workflows/test-with-bats.yml
